[package]
license-file = "licence.md"
description = "A crate to generate enum impls which can list basic info about an enum."
categories = ["rust-patterns"]
repository = "https://github.com/CalinZBaenen/enum-info"
keywords = ["enum", "variants", "counting", "macro"]
authors = ["Calin Baenen <calinbaenen@gmail.com>"]
edition = "2024"
license = "MIT"
version = "1.0.3"
name = "enum-info"

[lib]
crate-type = ["proc-macro"]
proc-macro = true
name = "enum_info"